function [sdir,file,filter,dsf,thresh,onset,offset,minInt,foi,bands,cycles,ftimwin,overlap,cohMethod,eoi,saveParent] = scbParamsSingle
sdir = 'C:\Users\Lucas\Desktop\GreenLab\data\WilderBinge\channel_renamed\';
%sdir = 'C:\Users\Lucas\Desktop\GreenLab\data\twoSiteStim\editedWithSleep\';
file = 'H13BaseNov12';
%file = '5HzR_N7_PreStim_9_8_16';
filter = 'y';
dsf = 5;
thresh = 2; 
onset = 5;
offset = 17000;
minInt = 3;
foi = [1 2 100];
bands = {'theta',[4,8];'alpha',[9,12];'beta',[13,30];'lgam',[45,65];'hgam',[70,90]};
cycles = 5;
ftimwin = [];
overlap = 0.5;
cohMethod = 'mat';
eoi = {'binge',[0 3];'notbinge',[0 3]};
saveParent = 'C:\Users\Lucas\Desktop\GreenLab\data\test\';
