function [sdir,file,filter,dsf,thresh,onset,offset,minInt,foi,bands,cycles,ftimwin,overlap,cohMethod,eoi,saveParent] = scbParamsSingle
sdir = 'C:\Users\Lucas\Desktop\GreenLab\data\WilderBinge\channel_renamed\';
%sdir = 'C:\Users\Lucas\Desktop\GreenLab\data\twoSiteStim\editedWithSleep\';
file = 'H10RegChowNov23';
%file = '5HzR_N7_PreStim_9_8_16';
filter = 'y';
dsf = 5;
thresh = 2; 
onset = 50;
offset = 17000;
minInt = 10;
foi = [1 2 100];
bands = {'theta',[4,7];'alpha',[8,13];'beta',[15,30];'lgam',[45,65];'hgam',[70,90]};
cycles = 3;
ftimwin = [];
overlap = 0.5;
cohMethod = 'mat';
eoi = {'rest',[0 10]};
saveParent = 'C:\Users\Lucas\Desktop\GreenLab\data\fullAnalysisTest\';
