function [sdir,file,filter,dsf,thresh,onset,offset,minInt,foi,bands,cycles,ftimwin,overlap,cohMethod,eoi,saveParent] = scbParamsMulti(file)
%sdir = 'C:\Users\Lucas\Desktop\GreenLab\data\WilderBinge\channel_renamed\';
sdir = 'C:\Users\Lucas\Desktop\GreenLab\data\twoSiteStim\edited\';
%file = 'H10RegChowNov23';
file = file;
filter = 'y';
dsf = 5;
thresh = 2; 
onset = 5;
offset = 17000;
minInt = 30;
foi = [1 2 150];
bands = {'theta',[4,7];'alpha',[8,13];'beta',[15,30];'lgam',[45,65];'hgam',[70,90]};
cycles = 3;
ftimwin = [];
overlap = 0.5;
cohMethod = 'mat';
eoi = {'full',[0 3]};
saveParent = 'C:\Users\Lucas\Desktop\GreenLab\data\twoSiteStim\test\';